
server:
  port: 9901

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/knowledgemindmapdb?serverTimezone=Asia/Shanghai&chracterEncoding=utf-8
    username: root
    password: 19981024
  jpa:
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        hbm2ddl.auto: none
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect